local M = {}

--- @param c Colorscheme The color palette
function M.get(c, _, _)
  return {
    NeogitGraphAuthor             = { fg = c.base.cyan },
    NeogitGraphRed                = { fg = c.base.red },
    NeogitGraphWhite              = { fg = c.base.white },
    NeogitGraphYellow             = { fg = c.base.yellow },
    NeogitGraphGreen              = { fg = c.base.green },
    NeogitGraphCyan               = { fg = c.base.cyan },
    NeogitGraphBlue               = { fg = c.base.blue },
    NeogitGraphPurple             = { fg = c.base.magenta },
    NeogitGraphGray               = { fg = c.base.dimmed3 },
    NeogitGraphOrange             = { fg = c.base.orange },
    NeogitGraphBoldOrange         = { fg = c.base.orange, bold = true },
    NeogitGraphBoldRed            = { fg = c.base.red, bold = true },
    NeogitGraphBoldWhite          = { fg = c.base.white, bold = true },
    NeogitGraphBoldYellow         = { fg = c.base.yellow, bold = true },
    NeogitGraphBoldGreen          = { fg = c.base.green, bold = true },
    NeogitGraphBoldCyan           = { fg = c.base.cyan, bold = true },
    NeogitGraphBoldBlue           = { fg = c.base.blue, bold = true },
    NeogitGraphBoldPurple         = { fg = c.base.magenta, bold = true },
    NeogitGraphBoldGray           = { fg = c.base.dimmed3, bold = true },
    NeogitSubtleText              = { link = "Comment" },
    NeogitSignatureGood           = { link = "NeogitGraphGreen" },
    NeogitSignatureBad            = { link = "NeogitGraphBoldRed" },
    NeogitSignatureMissing        = { link = "NeogitGraphPurple" },
    NeogitSignatureNone           = { link = "NeogitSubtleText" },
    NeogitSignatureGoodUnknown    = { link = "NeogitGraphBlue" },
    NeogitSignatureGoodExpired    = { link = "NeogitGraphOrange" },
    NeogitSignatureGoodExpiredKey = { link = "NeogitGraphYellow" },
    NeogitSignatureGoodRevokedKey = { link = "NeogitGraphRed" },
    NeogitCursorLine              = { link = "CursorLine" },
    NeogitHunkMergeHeader         = { fg = c.editor.background, bg = c.editor.selectionBackground, bold = true },
    NeogitHunkMergeHeaderHighlight= { fg = c.editor.background, bg = c.base.cyan, bold = true },
    NeogitHunkMergeHeaderCursor   = { fg = c.editor.background, bg = c.base.cyan, bold = true },
    NeogitHunkHeader              = { fg = c.editor.background, bg = c.base.dimmed3, bold = true },
    NeogitHunkHeaderHighlight     = { fg = c.editor.background, bg = c.base.magenta, bold = true },
    NeogitHunkHeaderCursor        = { fg = c.editor.background, bg = c.base.magenta, bold = true },
    NeogitDiffContext             = { bg = c.base.dark1 },
    NeogitDiffContextHighlight    = { bg = c.base.dark1 },
    NeogitDiffContextCursor       = { bg = c.base.dark1 },
    NeogitDiffAdditions           = { fg = c.gitDecoration.addedResourceForeground },
    NeogitDiffAdd                 = { bg = c.diffEditor.insertedLineBackground, fg = c.gitDecoration.addedResourceForeground },
    NeogitDiffAddHighlight        = { bg = c.diffEditor.insertedLineBackground, fg = c.base.green },
    NeogitDiffAddCursor           = { bg = c.base.dark, fg = c.base.green },
    NeogitDiffDeletions           = { fg = c.gitDecoration.deletedResourceForeground },
    NeogitDiffDelete              = { bg = c.diffEditor.removedLineBackground, fg = c.gitDecoration.deletedResourceForeground },
    NeogitDiffDeleteHighlight     = { bg = c.diffEditor.removedLineBackground, fg = c.base.red },
    NeogitDiffDeleteCursor        = { bg = c.base.dark, fg = c.base.red },
    NeogitPopupSectionTitle       = { link = "Function" },
    NeogitPopupBranchName         = { link = "String" },
    NeogitPopupBold               = { bold = true },
    NeogitPopupSwitchKey          = { fg = c.base.magenta },
    NeogitPopupSwitchEnabled      = { link = "SpecialChar" },
    NeogitPopupSwitchDisabled     = { link = "NeogitSubtleText" },
    NeogitPopupOptionKey          = { fg = c.base.magenta },
    NeogitPopupOptionEnabled      = { link = "SpecialChar" },
    NeogitPopupOptionDisabled     = { link = "NeogitSubtleText" },
    NeogitPopupConfigKey          = { fg = c.base.magenta },
    NeogitPopupConfigEnabled      = { link = "SpecialChar" },
    NeogitPopupConfigDisabled     = { link = "NeogitSubtleText" },
    NeogitPopupActionKey          = { fg = c.base.magenta },
    NeogitPopupActionDisabled     = { link = "NeogitSubtleText" },
    NeogitFilePath                = { fg = c.base.cyan, italic = true },
    NeogitCommitViewHeader        = { bg = c.base.magenta, fg = c.editor.background },
    NeogitCommitViewDescription   = { link = "String" },
    NeogitDiffHeader              = { bg = c.base.dimmed5, fg = c.base.cyan, bold = true },
    NeogitDiffHeaderHighlight     = { bg = c.base.dimmed5, fg = c.base.magenta, bold = true },
    NeogitCommandText             = { link = "NeogitSubtleText" },
    NeogitCommandTime             = { link = "NeogitSubtleText" },
    NeogitCommandCodeNormal       = { link = "String" },
    NeogitCommandCodeError        = { link = "Error" },
    NeogitBranch                  = { fg = c.base.cyan, bold = true },
    NeogitBranchHead              = { fg = c.base.cyan, bold = true, underline = true },
    NeogitRemote                  = { fg = c.base.green, bold = true },
    NeogitUnmergedInto            = { fg = c.base.magenta, bold = true },
    NeogitUnpushedTo              = { fg = c.base.magenta, bold = true },
    NeogitUnpulledFrom            = { fg = c.base.magenta, bold = true },
    NeogitStatusHEAD              = {},
    NeogitObjectId                = { link = "NeogitSubtleText" },
    NeogitStash                   = { link = "NeogitSubtleText" },
    NeogitRebaseDone              = { link = "NeogitSubtleText" },
    NeogitFold                    = { fg = "None", bg = "None" },
    NeogitChangeMuntracked        = { link = "NeogitChangeModified" },
    NeogitChangeAuntracked        = { link = "NeogitChangeAdded" },
    NeogitChangeNuntracked        = { link = "NeogitChangeNewFile" },
    NeogitChangeDuntracked        = { link = "NeogitChangeDeleted" },
    NeogitChangeCuntracked        = { link = "NeogitChangeCopied" },
    NeogitChangeUuntracked        = { link = "NeogitChangeUpdated" },
    NeogitChangeRuntracked        = { link = "NeogitChangeRenamed" },
    NeogitChangeDDuntracked       = { link = "NeogitChangeUnmerged" },
    NeogitChangeUUuntracked       = { link = "NeogitChangeUnmerged" },
    NeogitChangeAAuntracked       = { link = "NeogitChangeUnmerged" },
    NeogitChangeDUuntracked       = { link = "NeogitChangeUnmerged" },
    NeogitChangeUDuntracked       = { link = "NeogitChangeUnmerged" },
    NeogitChangeAUuntracked       = { link = "NeogitChangeUnmerged" },
    NeogitChangeUAuntracked       = { link = "NeogitChangeUnmerged" },
    NeogitChangeUntrackeduntracked = { fg = "None" },
    NeogitChangeMunstaged         = { link = "NeogitChangeModified" },
    NeogitChangeAunstaged         = { link = "NeogitChangeAdded" },
    NeogitChangeNunstaged         = { link = "NeogitChangeNewFile" },
    NeogitChangeDunstaged         = { link = "NeogitChangeDeleted" },
    NeogitChangeCunstaged         = { link = "NeogitChangeCopied" },
    NeogitChangeUunstaged         = { link = "NeogitChangeUpdated" },
    NeogitChangeRunstaged         = { link = "NeogitChangeRenamed" },
    NeogitChangeDDunstaged        = { link = "NeogitChangeUnmerged" },
    NeogitChangeUUunstaged        = { link = "NeogitChangeUnmerged" },
    NeogitChangeAAunstaged        = { link = "NeogitChangeUnmerged" },
    NeogitChangeDUunstaged        = { link = "NeogitChangeUnmerged" },
    NeogitChangeUDunstaged        = { link = "NeogitChangeUnmerged" },
    NeogitChangeAUunstaged        = { link = "NeogitChangeUnmerged" },
    NeogitChangeUAunstaged        = { link = "NeogitChangeUnmerged" },
    NeogitChangeUntrackedunstaged = { fg = "None" },
    NeogitChangeMstaged           = { link = "NeogitChangeModified" },
    NeogitChangeAstaged           = { link = "NeogitChangeAdded" },
    NeogitChangeNstaged           = { link = "NeogitChangeNewFile" },
    NeogitChangeDstaged           = { link = "NeogitChangeDeleted" },
    NeogitChangeCstaged           = { link = "NeogitChangeCopied" },
    NeogitChangeUstaged           = { link = "NeogitChangeUpdated" },
    NeogitChangeRstaged           = { link = "NeogitChangeRenamed" },
    NeogitChangeDDstaged          = { link = "NeogitChangeUnmerged" },
    NeogitChangeUUstaged          = { link = "NeogitChangeUnmerged" },
    NeogitChangeAAstaged          = { link = "NeogitChangeUnmerged" },
    NeogitChangeDUstaged          = { link = "NeogitChangeUnmerged" },
    NeogitChangeUDstaged          = { link = "NeogitChangeUnmerged" },
    NeogitChangeAUstaged          = { link = "NeogitChangeUnmerged" },
    NeogitChangeUAstaged          = { link = "NeogitChangeUnmerged" },
    NeogitChangeUntrackedstaged   = { fg = "None" },
    NeogitChangeModified          = { fg = c.gitDecoration.modifiedResourceForeground, bold = true, italic = true },
    NeogitChangeAdded             = { fg = c.gitDecoration.addedResourceForeground, bold = true, italic = true },
    NeogitChangeDeleted           = { fg = c.gitDecoration.deletedResourceForeground, bold = true, italic = true },
    NeogitChangeRenamed           = { fg = c.base.magenta, bold = true, italic = true },
    NeogitChangeUpdated           = { fg = c.base.orange, bold = true, italic = true },
    NeogitChangeCopied            = { fg = c.base.cyan, bold = true, italic = true },
    NeogitChangeUnmerged          = { fg = c.base.dimmedRed, bold = true, italic = true },
    NeogitChangeNewFile           = { fg = c.gitDecoration.addedResourceForeground, bold = true, italic = true },
    NeogitSectionHeader           = { fg = c.base.magenta, bold = true },
    NeogitSectionHeaderCount      = {},
    NeogitUntrackedfiles          = { link = "NeogitSectionHeader" },
    NeogitUnstagedchanges         = { link = "NeogitSectionHeader" },
    NeogitUnmergedchanges         = { link = "NeogitSectionHeader" },
    NeogitUnpulledchanges         = { link = "NeogitSectionHeader" },
    NeogitUnpushedchanges         = { link = "NeogitSectionHeader" },
    NeogitRecentcommits           = { link = "NeogitSectionHeader" },
    NeogitStagedchanges           = { link = "NeogitSectionHeader" },
    NeogitStashes                 = { link = "NeogitSectionHeader" },
    NeogitMerging                 = { link = "NeogitSectionHeader" },
    NeogitBisecting               = { link = "NeogitSectionHeader" },
    NeogitRebasing                = { link = "NeogitSectionHeader" },
    NeogitPicking                 = { link = "NeogitSectionHeader" },
    NeogitReverting               = { link = "NeogitSectionHeader" },
    NeogitTagName                 = { fg = c.base.yellow },
    NeogitTagDistance             = { fg = c.base.cyan },
    NeogitFloatHeader             = { bg = c.base.dark, bold = true },
    NeogitFloatHeaderHighlight    = { bg = c.base.dimmed5, fg = c.base.cyan, bold = true },
  }
end

return M
